import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/components/ClientProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ElectraBazaar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientProvider>
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
    </ClientProvider>
  );
}
